// Code generated by mockery v1.0.0. DO NOT EDIT.

package httpxmock

import mock "github.com/stretchr/testify/mock"

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

// RecordCount provides a mock function with given fields: key
func (_m *Metrics) RecordCount(key string) {
	_m.Called(key)
}
